spring.application.name=chipcook-api
spring.datasource.url=${JDBC_DATABASE_URL:${DATABASE_URL:${DB_URL:jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:chipcook}}}}
spring.datasource.username=${PGUSER:${DB_USERNAME:postgres}}
spring.datasource.password=${PGPASSWORD:${DB_PASSWORD:12345}}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.multitenancy.strategy=SCHEMA

jwt.secret=${JWT_SECRET:chipcook-secret-key-muito-longa-para-seguranca-256bits-minimum-realmente}
jwt.expiration=${JWT_EXPIRATION:86400000}
